apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: oulogin
spec:
  version: {{ .TagName }}
  homepage: https://github.com/TremoloSecurity/kubectl-login
  platforms:
  - selector:
      matchLabels:
        os: darwin
    {{addURIAndSha "https://nexus.tremolo.io/repository/oulogin/oulogin-{{ .TagName }}-macos.zip" {{ .TagName }} }}
    bin: oulogin
  - selector:
      matchLabels:
        os: linux
    {{addURIAndSha "https://nexus.tremolo.io/repository/oulogin/oulogin-{{ .TagName }}-linux.zip" {{ .TagName }} }}
    bin: oulogin
  - selector:
      matchLabels:
        os: windows
    {{addURIAndSha "https://nexus.tremolo.io/repository/oulogin/oulogin-{{ .TagName }}-win.zip" {{ .TagName }} }}
    bin: oulogin
  shortDescription: "Login to a cluster via OpenUnison"
  description: |
    Launches a browser to login to the cluster via OpenUnison.  OpenUnison's 
    certificate MUST be trusted by the local system.  